language: node_js
node_js: 6
sudo: false
cache:
  bundler: true
  directories:
  # - $HOME/[path]

env:
  global:
  - JEKYLL_ENV=production
  - LATEST_RELEASE=2.2.0

before_install:
  - source ./scripts/env-set.sh
  - ./scripts/install-dart-sdk.sh
  - ./scripts/before-install.sh
  - rvm install 2.3.0

install:
  - ./scripts/install.sh
  - ./scripts/get-ng-repo.sh

before_script:
  - gulp dartdoc --dgeni-log=warn

script:
  # - ./deploy/runtests.sh
  # - ./deploy/cibuild
  # We use --fast to avoid setting up the fragments again;
  # since it was done via `gulp dartdoc` above.
  - gulp build --fast --dgeni-log=warn

after_script:
  - ./scripts/check-build.sh
  - ./scripts/check-links.sh

# branch whitelist
# branches:
#   only:
#   - master        # test the master branch
#   - /stage-(.*)/  # test every branch which starts with "stage-"

deploy:
  - provider: script
    script: ./deploy/deploy-firebase.sh
    skip_cleanup: true
    on:
      branch: master
