dist: trusty
sudo: required
language: node_js
node_js: 6

# cache:
#   bundler: true
#   directories:
#   - $HOME/[path]

env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
    - JEKYLL_ENV=production
  matrix:
    - CI_TASK=build
    - CI_TASK=test
    - CI_TASK="e2e --fast"

matrix:
  fast_finish: true
  allow_failures:
    - env: CI_TASK="e2e --fast"

before_install:
  - source ./scripts/env-set.sh
  - ./scripts/before-install.sh
  - rvm reload && rvm current

install:
  - ./scripts/install.sh

before_script:
  - ./scripts/browser.sh

script:
  # - ./scripts/deploy/runtests.sh; ./scripts/deploy/cibuild
  - gulp $CI_TASK

after_script:
  - ./scripts/check-build.sh || travis_terminate 1
  - ./scripts/check-links.sh || travis_terminate 1

# branch whitelist
# branches:
#   only:
#   - master        # test the master branch
#   - /stage-(.*)/  # test every branch which starts with "stage-"

deploy:
  - provider: script
    script: ./scripts/deploy/firebase.sh
    skip_cleanup: true
    on:
      repo: dart-lang/site-webdev
      branch: master
      condition: $CI_TASK == build*
