language: node_js
node_js: 6
sudo: false
cache:
  bundler: true
  directories:
  # - $HOME/[path]

env:
  global:
  - JEKYLL_ENV=production
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
  - LATEST_RELEASE=2.2.0

before_install:
  - source ./scripts/env-set.sh
  - ./scripts/before-install.sh
  - rvm install 2.3.0

install:
  - ./scripts/install.sh
  - ./scripts/install-dart-sdk.sh
  - ./scripts/get-ng-repo.sh
  - ./scripts/install-ng-repo.sh

before_script:
  # If needed, we can do less than a full site-refresh, but this will do for now:
  - gulp site-refresh
  - gulp dartdoc

script:
  # - ./deploy/runtests.sh
  # - ./deploy/cibuild
  - gulp build
  - ./scripts/check-build.sh

# branch whitelist
# branches:
#   only:
#   - master        # test the master branch
#   - /stage-(.*)/  # test every branch which starts with "stage-"

# after_success:
# We could add the deployment to firebase here if there are no additional customizations etc...

deploy:
  - provider: script
    script: ./deploy/deploy-firebase.sh
    skip_cleanup: true
    on:
      branch: master

after_deploy:
  # Just FYI test. Won't fail the build if it has errors.
  - ./deploy/html_proof.rb
  # # Checks for bad HTML, broken links, and forces build to fail if it fails.
  # # (By default, Travis doesn't fail builds after deployment.)
  # - "./deploy/html_proof.rb || travis_terminate 1"